# See owfs.conf.md for possible entries: Edit it yourself
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# --- ALL PROGAMS ---------------------------------------
# > valid for all
Celsius # Celsius (default) temperature scale

error_level = 0  # Choose verbosity of error/debugging reports 0=low 9=high
# =0 default errors only
# =1 connections/disconnections
# =2 all high level calls
# =3 data summary for each call
# =4 details level
# >4 debugging chaff

error_print = 1  # Where debug info is placed 0-mixed 1-syslog 2-console
# =0 default mixed destination: stderr foreground / syslog background
# =1 syslog only
# =2 stderr only
# =3 /dev/null (quiet mode).

# --- OWSERVER ------------------------------------------
server: usb          # for USB device: DS9490R
server: port = 4304  # Standard Port 

# --- All other beside! OWSERVER ------------------------
! server: server = 127.0.0.1:4304  # owfs, owhttdp, owftpd uses existing server

# --- OWFS ----------------------------------------------
mountpoint = /mnt/1wire # Folder needs to exits!
allow_other             # Allow other users to see owfs file system needs /etc/fuse.conf setting

# --- OWHTTPD -------------------------------------------
http: port = 2120

# --- OWFTPD --------------------------------------------
# Not used currently in container, but for completeness
ftp: port = 2121